[project]
name = "crawler"
version = "0.1.0"
description = "Sistema de busca e download de bibliografia em PDF"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "playwright",
    "playwright-stealth",
    "fake-useragent",
    "pymupdf>=1.26.7",
]
